<?php
/**
 * @file
 * Main file to hold Company Domain specific hook code.
 */

require_once 'company.features.inc';
require_once 'includes/Company.inc';
require_once 'includes/CompanyEntityForm.inc';


/**
 * Implements hook_form_alter().
 */
function company_form_alter(&$form, &$form_state, $form_id) {
  $company_form = new CompanyEntityForm($form);
  $company_form->hookForm();
  if ($form_id == 'views_exposed_form' && $form['#action'] == '/company/multi-search') {
    $form['company_name']['#type'] = 'textarea';
  }
}

/**
 * Implements hook_views_pre_render().
 */
function company_views_pre_render(&$view) {
  $company = new Company();
  $company->viewsPreRender($view);
  return $view;
}

/**
 * Implements hook_views_query_alter().
 */
function company_views_query_alter(&$views) {
  // Alter the view query to do multiple searches on company_name.
  if ($views->name == 'company_search' && $views->current_display == 'page_1') {
    unset ($views->query->where);
    $views->query->set_where_group('OR', 0);

    $lines = explode("\n", $views->exposed_raw_input['company_name']);
    foreach ($lines as $line) {
      $value = '%' . trim($line) . '%';
      $views->query->add_where(0, 'company_name', $value, 'LIKE');
    }
  }
}
