<?php
/**
 * @file
 * Main file to hold Copany Domain specific hook code.
 */

require_once 'company.features.inc';
require_once 'includes/Company.inc';
require_once 'includes/CompanyEntityForm.inc';


/**
 * Implements hook_form_alter().
 */
function company_form_alter(&$form, &$form_state, $form_id) {
  $company_form = new CompanyEntityForm($form);
  $company_form->hookForm();
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function company_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panelizer') {
    return "plugins/$plugin_type";
  }
}
