<?php
/**
 * @file
 * Code for the person feature.
 */

#include_once 'person.features.inc';
#include_once 'includes/Person.inc';

function person_views_pre_render(&$view) {
  if ($view->name == "person_search") {
    foreach ($view->result as &$result) {
      $fields = array('field_phone_number_entity', 'field_phone_entity');
      $result = _result_field_combine($result, $fields);
    }
  }
  return $view;
}

/**
 * Combines multiple fields with the same structure
 * @result is a view's result object
 * @fields is a simple array of the fields to combine. All fields will be merged
 * into the first listed field
 */
function _result_field_combine($result, $fields) {
  foreach ($fields as $field) {
    $field_values[] = $result->$field;
  }
  $result->$fields[0] = call_user_func_array('array_merge', $field_values);
  return $result;
}

