<?php
/**
 * @file
 * The CDB module will hold global domain space logic.
 */

include_once 'cdb.features.inc';
include_once 'includes/CdbEntity.inc';
include_once 'includes/EntityForm.inc';

/**
 * Implements hook_preprocess().
 */
function cdb_preprocess_page(&$variable) {
  $variable['navigation_nice_menu'] = _cdb_get_navigation_nice_menus();
}

/**
 * Implements hook_entity_info_alter().
 */
function cdb_entity_info_alter(&$entity_info) {
  // Change some Cdb Entity defaults.
  $cdb_entities = get_cdb_entities();
  foreach ($cdb_entities as $entity) {
    $cdb_entity =&  $entity_info[$entity]['bundles'][$entity];
    $cdb_entity['crud']['add']['path'] = "$entity/add";
    $cdb_entity['crud']['view']['path'] = "$entity/%";
    $cdb_entity['crud']['edit']['path'] = "$entity/%/edit";
    $cdb_entity['crud']['delete']['path'] = "$entity/%/delete";
  }
}

/**
 * Implements hook_permission().
 */
function cdb_permission() {
  $perms = array();
  foreach (get_cdb_entities() as $entity) {
    // Create.
    $perms["$entity add"] = array(
      'title' => "Add new $entity",
      'description' => "Users with this permission may add new $entity records to the database.",
    );
    // Read.
    $perms["$entity view"] = array(
      'title' => "View $entity",
      'description' => "Users with this permission may view records of type $entity.",
    );
    // Update.
    $perms["$entity edit"] = array(
      'title' => "Edit $entity",
      'description' => "Users with this permission may edit records of type $entity.",
    );
    // Delete.
    $perms["$entity delete"] = array(
      'title' => "Delete $entity",
      'description' => "Users with this permission may delete records of type $entity.",
    );
  }
  return $perms;
}


/**
 * Returns navigation links as nice_menus.
 */
function _cdb_get_navigation_nice_menus() {
  $variable['id'] = 2;
  $variable['direction'] = 'horizontal';
  $variable['menu_name'] = 'navigation';
  $variable['depth'] = 3;

  $output = theme('nice_menus', $variable);

  return $output['content'];
}

/**
 * Returns a list of CDB entities.
 */
function get_cdb_entities() {
  return array('company', 'person', 'barcode', 'phone_number', 'address');
}
